name: 🎮 Submit New Mod
description: Submit a new mod to the PalSchema Mod Store
title: "[MOD SUBMISSION] "
labels: ["mod-submission", "pending-review"]
assignees:
  - GungnirIncarnate
body:
  - type: markdown
    attributes:
      value: |
        # 🎮 Mod Submission Form
        
        Thank you for contributing to the PalSchema Mod Store! Please fill out all the required information below.
        
        **⚠️ Important**: Make sure your mod works with PalSchema and follows our guidelines.

  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: The display name of your mod
      placeholder: "Enhanced Pal Stats"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Current version of your mod (e.g., 1.0.0)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of what your mod does
      placeholder: "This mod enhances the display of Pal statistics..."
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: Your name or username
      placeholder: "YourUsername"
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: Tags (select all that apply)
      multiple: true
      options:
        - ui
        - enhancement
        - statistics
        - quality-of-life
        - breeding
        - combat
        - inventory
        - automation
        - visual
        - performance
        - utility
        - gameplay
        - other
    validations:
      required: true

  - type: input
    id: min-game-version
    attributes:
      label: Minimum Game Version
      description: Minimum Palworld version required
      placeholder: "0.3.0"
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: Homepage (optional)
      description: Link to your mod's homepage or documentation
      placeholder: "https://github.com/yourusername/your-mod"

  - type: input
    id: source-code
    attributes:
      label: Source Code (optional)
      description: Link to your mod's source code
      placeholder: "https://github.com/yourusername/your-mod"

  - type: textarea
    id: download-links
    attributes:
      label: Download Links
      description: |
        Provide direct download links to your mod files. Include:
        - Main mod zip file
        - Icon (PNG/JPG, recommended 128x128 pixels)
        
        You can upload files to GitHub releases, Google Drive, Dropbox, etc.
      placeholder: |
        Mod ZIP: https://github.com/yourusername/your-mod/releases/download/v1.0.0/YourMod-v1.0.0.zip
        Icon: https://github.com/yourusername/your-mod/raw/main/icon.png
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements Check
      description: Please confirm the following
      options:
        - label: My mod is compatible with PalSchema
          required: true
        - label: My mod does not contain malicious code
          required: true
        - label: I have tested my mod and it works correctly
          required: true
        - label: I have the right to distribute this mod
          required: true
        - label: I understand this mod will be publicly available
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information you'd like to share about your mod
      placeholder: "Known issues, future plans, special thanks, etc."