name: Update Manifest

on:
  push:
    branches: [ main ]
    paths: [ 'mods/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'mods/**' ]
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Validate mods
      run: |
        python scripts/validate-mod.py
      continue-on-error: false
    
    - name: Generate manifest
      run: |
        python scripts/generate-manifest.py
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet manifest.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit updated manifest
      if: steps.changes.outputs.changed == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add manifest.json
        git commit -m "🤖 Auto-update manifest.json"
        git push
    
    - name: Upload manifest as artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifest
        path: manifest.json
    
    - name: Comment on PR
      if: github.event_name == 'pull_request' && steps.changes.outputs.changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
          const modCount = manifest.mods.length;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🤖 **Manifest Update Preview**\n\n` +
                  `This PR will update the manifest with **${modCount} total mods**.\n\n` +
                  `The manifest will be automatically updated when this PR is merged.`
          });